name: Run PHPStan

on: [push]

jobs:
  run-phpstan:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 'latest'
          coverage: none
          tools: composer, cs2pr
      - name: Install PHP dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: '--prefer-dist --no-scripts'
      - name: PHPStan
        run: composer phpstan
